[package]
name = "probe-rs"
version = "0.10.1"
authors = ["Noah Hüsser <yatekii@yatekii.ch>", "Dominik Boehi <dominik.boehi@gmail.ch>"]
edition = "2018"
description = "A collection of on chip debugging tools to communicate with microchips."
documentation = "https://docs.rs/probe-rs/"
homepage = "https://github.com/probe-rs/probe-rs"
repository = "https://github.com/probe-rs/probe-rs"
readme = "../README.md"
categories = ["embedded", "hardware-support", "development-tools::debugging"]
keywords = ["embedded"]
license = "MIT OR Apache-2.0"

[features]
default = ["builtin-targets"]

# Enable all built in targets.
builtin-targets = []

ftdi = ["libftdi1-sys"]

[dependencies]
log = "0.4.8"
num-traits = "0.2.11"
enum-primitive-derive = "0.2.1"
jep106 = "0.2.4"
scroll = "0.10.1"
rusb = "0.7.0"
lazy_static = "1.4.0"
hidapi = "1.2.0"
gimli = "0.23.0"
object = "0.23.0"
bitfield = "0.13.2"
serde = { version = "1.0.104", features = ["derive"] }
serde_yaml = "0.8.11"
ihex = "3.0.0"
hexdump = { version = "0.1.0", optional = true }
thiserror = "1.0.10"
jaylink = "0.1.4"
base64 = "0.13.0"
svg = "0.8.0"
anyhow = "1.0.31"
bitvec = {version = "0.20.1" }
libftdi1-sys = { version = "1.0.0-alpha3", optional = true }
static_assertions = "1.1.0"

[build-dependencies]
probe-rs-t2rust  = { path = "../probe-rs-t2rust", version ="0.7.0" }

[dev-dependencies]
rand = "0.8.0"
structopt = "0.3"
pretty_env_logger = "0.4.0"
serde_json = "1.0.47"
reqwest = { version = "0.11.0", features = ["blocking", "json"] }
chrono = "0.4.19"
serde = "1.0.118"